# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go: ["~1.16", "^1.17"]

    name: Linux Go ${{ matrix.go }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          fetch-depth: '0' # 0 indicates all history for all branches and tags.
      - uses: actions/setup-go@v2 # See https://github.com/actions/setup-go
        with:
          stable: 'false'
          go-version: ${{ matrix.go }}

      - name: Build
        run: |
          export GO111MODULE=on
          go version
          make

      - name: Test
        run: make test

  macos:
    # The type of runner that the job will run on
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        go: ["~1.14"]

    name: macOS Go ${{ matrix.go }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          fetch-depth: '0' # 0 indicates all history for all branches and tags.
      - uses: actions/setup-go@v2 # See https://github.com/actions/setup-go
        with:
          stable: 'false'
          go-version: ${{ matrix.go }}

      - name: Build
        run: |
          export GO111MODULE=on
          go version
          make

      - name: Test
        run: make test
